Meeting summary fixes.
APDevTeam/Movecraft pull request #327
Opened 2020-09-10 05:12 UTC by drfiveminusmint

This pull request changes two things:
1) Changes crew bed respawning to find an open space on ground next to the bed and spawn them there rather than spawning them on top of the bed.
2) Teleports the player one block higher when using /manoverboard to prevent them being stuck inside a block.

### Checklist
- [x] Proper internationalization
- [x] Compiled/tested

2020-09-10 14:59 UTC, TylerS1066 requested changes
Once the debug message is removed, and this is confirmed to be working, looks good to me!

2020-09-10 14:59 UTC, TylerS1066 commented on modules/Movecraft/src/main/java/net/countercraft/movecraft/sign/CrewSign.java
> +                        player.sendMessage("Found a spot to respawn player!");
Looks like a debug message was left in.

2020-09-10 16:23 UTC, drfiveminusmint commented on modules/Movecraft/src/main/java/net/countercraft/movecraft/sign/CrewSign.java
> +                        player.sendMessage("Found a spot to respawn player!");
Whoops lemme fix that :facepalm:

2020-09-10 16:23 UTC, TylerS1066 approved these changes

2020-09-10 16:24 UTC, TylerS1066 commented
@cccm5 or @eirikh1996 want to review this?

2020-09-11 16:59 UTC, eirikh1996 requested changes

2020-09-11 16:59 UTC, eirikh1996 commented on modules/Movecraft/src/main/java/net/countercraft/movecraft/sign/CrewSign.java
> +               respawnLoc = new Location(craft.getW(), respawnLoc.getX()+0.5, respawnLoc.getY(), respawnLoc.getZ()+0.5);
Use add() to add coordinates instead of making a new location

2020-09-12 17:24 UTC, drfiveminusmint commented
Requested changes have been made

2020-09-12 18:11 UTC, eirikh1996 approved these changes

2020-09-12 18:12 UTC, merged