Movecraft-Warfare
APDevTeam/Movecraft pull request #346
Opened 2020-12-27 15:24 UTC by TylerS1066

### Describe in detail what your pull request acomplishes
See #312.

### Checklist
- [ ] Unit tests 
- [ ] Proper internationalization
- [ ] Compiled/tested

2021-01-07 22:33 UTC, TylerS1066 commented
@cccm5 @eirikh1996 @drfiveminusmint I am once again asking you for PR reviews.

2021-01-08 01:02 UTC, eirikh1996 requested changes

2021-01-08 01:02 UTC, eirikh1996 commented on modules/Movecraft/pom.xml
> +    <version>7.0.0_beta_6</version>
Isn't this supposed to be beta 7 instead of beta 6?

2021-01-08 01:22 UTC, eirikh1996 approved these changes

2021-01-08 01:23 UTC, merged