Possibly fixed a few NPEs regarding null piloted crafts
APDevTeam/Movecraft pull request #361
Opened 2021-02-06 21:41 UTC by TylerS1066

### Checklist
- [ ] Unit tests 
- [ ] Proper internationalization
- [ ] Compiled/tested

2021-02-06 21:44 UTC, TylerS1066 commented
This possible logic issue has been patched,

2021-02-12 02:45 UTC, TylerS1066 commented
@cccm5 @eirikh1996 can one of you review this?  I'd like to get this included soon.

2021-02-17 23:35 UTC, cccm5 requested changes

2021-02-17 23:35 UTC, cccm5 commented on modules/Movecraft/src/main/java/net/countercraft/movecraft/async/AsyncManager.java
> +                                notification += I18nSupport.getInternationalisedString("Contact/Subcraft Rotate - North");
Use brackets

2021-02-17 23:35 UTC, cccm5 commented on modules/Movecraft/src/main/java/net/countercraft/movecraft/commands/ReleaseCommand.java
> +                if(craft.getNotificationPlayer() == null) {
don't touch this

2021-02-17 23:35 UTC, cccm5 commented on modules/Movecraft/src/main/java/net/countercraft/movecraft/craft/ICraft.java
> +            if(getNotificationPlayer() != null)
don't touch this

2021-02-17 23:35 UTC, cccm5 commented on modules/Movecraft/src/main/java/net/countercraft/movecraft/worldguard/WorldGuardCompatManager.java
> +            if(!Movecraft.getInstance().getWorldGuardPlugin().canBuild(event.getCraft().getNotificationPlayer(), location.toBukkit(event.getCraft().getW()))){
don't touch this

2021-02-18 00:07 UTC, cccm5 approved these changes

2021-02-18 02:35 UTC, merged