Remove all the things
APDevTeam/Movecraft pull request #362
Opened 2021-02-06 22:06 UTC by TylerS1066

### Describe in detail what your pull request acomplishes
Movecraft-Repair removes repair functionality and will eventually allow addons such as Movecraft-Warfare to use a simple API for worldedit functions.  *This PR replaces #353.*

### Checklist
- [ ] Proper internationalization
- [ ] Compiled/tested

2021-02-12 00:26 UTC, TylerS1066 commented
@eirikh1996 @cccm5 @drfiveminusmint Movecraft-Repair is semi-stable and I don't foresee any further development needed in Movecraft itself to support the addon.  Movecraft-Warfare still has updates to support it, but that won't require a PR to this repo.

2021-02-12 00:34 UTC, cccm5 requested changes
Since we're no longer using it the worldedit dependency should be able to be safety removed from the build script. Furthermore, with repair being moved I believe we no longer make use of vault, so we could likely remove that as well (with the code loading it of course).

2021-02-12 00:57 UTC, TylerS1066 commented
> Since we're no longer using it the worldedit dependency should be able to be safety removed from the build script. Furthermore, with repair being moved I believe we no longer make use of vault, so we could likely remove that as well (with the code loading it of course).

Good catch, I also realized there was some internationalization and config stuff that needed removing.

2021-02-17 23:34 UTC, cccm5 approved these changes

2021-02-18 02:35 UTC, merged