Movecraft-Towny
APDevTeam/Movecraft pull request #381
Opened 2021-03-04 20:48 UTC by TylerS1066

### Describe in detail what your pull request acomplishes
Large WIP PR, mostly opened now to give a heads up and nice diff.  This will most likely be broken by #378 and other PRs and require replacement.

### Checklist
- [ ] Unit tests 
- [ ] Proper internationalization
- [ ] Compiled/tested

2021-03-05 16:45 UTC, TylerS1066 commented
[Movecraft-Towny](https://github.com/TylerS1066/Movecraft-Towny) is now public, with the v0.1.0 release supporting both this PR and in the future 1.14+.

2021-03-08 00:53 UTC, TylerS1066 commented
@cccm5 now that beta 9 is released this is ready for review.

2021-03-08 01:46 UTC, cccm5 requested changes
should be good after merge issues are resolved

2021-03-08 01:50 UTC, cccm5 approved these changes

2021-03-08 02:11 UTC, cccm5 approved these changes

2021-03-08 02:11 UTC, merged