Implement FluidLocations
APDevTeam/Movecraft pull request #460
Opened 2021-10-28 18:14 UTC by drfiveminusmint

This pull request implements the FluidLocations property of crafts.

### Related issues:
- This will close #446 

### Checklist
- [x] Proper internationalization
- [x] Compiled/tested

2021-11-06 13:01 UTC, TylerS1066 requested changes
Has this been tested to fix #446?

Other than that, I just have one comment about the tags.  We'd like to move away from checks against constant materials where possible.

2021-11-14 22:25 UTC, drfiveminusmint commented
requested changes made @TylerS1066

2021-11-14 22:25 UTC, drfiveminusmint commented
also, yes, it has been tested to close the issue

2021-11-15 23:10 UTC, TylerS1066 approved these changes

2021-11-15 23:11 UTC, merged