French language support
APDevTeam/Movecraft pull request #543
Opened 2022-08-20 21:58 UTC by HumorousFool

### Describe in detail what your pull request accomplishes
This PR cleans up the existing language files and adds a new one for french.

### Checklist
- [x] Proper internationalization
- [x] Tested

2022-08-20 22:02 UTC, TylerS1066 commented
I don't speak french, but it looks good to me!  I do have to review the removed and changed internationalization strings.

2022-08-28 21:55 UTC, TylerS1066 requested changes
I've not finished looking through the changes, but I've already found a number of issues.  Please review all removals you've made for usage in Movecraft.

2022-08-28 21:55 UTC, TylerS1066 commented on modules/Movecraft/src/main/resources/localisation/movecraftlang_cz.properties
> -Detection\ -\ Failed\ Craft\ is\ already\ being\ controlled=Stroj uz je nekym ovladan\!
This is something that should be used, but isn't currently.

2022-08-28 21:55 UTC, TylerS1066 commented on modules/Movecraft/src/main/resources/localisation/movecraftlang_cz.properties
>  Startup\ -\ Enabled\ message=[V %S] byl nacten.
Not needed for this PR, but I would like to remove internationalization from startup and console messages.  Unfortunately, we are unable to provide translations for all of our wiki material and as such we expect server owners to have a passable understanding of English console messages.

2022-08-28 21:55 UTC, TylerS1066 commented on modules/Movecraft/src/main/resources/localisation/movecraftlang_cz.properties
> -Release\ -\ Craft\ has\ been\ released\ message=Pustil jsi ovladani sveho stroje.
This message is still used.

2022-08-31 23:03 UTC, HumorousFool commented
I've re-added those messages double checked the rest of my deletions.

2022-09-23 23:34 UTC, TylerS1066 approved these changes

2022-09-23 23:40 UTC, merged