Interior blocks
APDevTeam/Movecraft pull request #561
Opened 2023-01-09 22:57 UTC by eirikh1996

### Describe in detail what your pull request accomplishes
This adds the interiorBlocks functionality to Movecraft. interiorBlocks are like allowedBlocks, but those blocks will only be detectable within a space enclosed to the bottom and the sides.

### Checklist
- [ ] Proper internationalization
- [ ] Tested

2023-01-09 23:01 UTC, TylerS1066 requested changes

2023-01-09 23:01 UTC, TylerS1066 commented on modules/Movecraft/src/main/resources/types/Airship.craft
> -        - 1.0
Same here, please rebase.

2023-01-09 23:01 UTC, TylerS1066 commented on modules/api/src/main/java/net/countercraft/movecraft/craft/Craft.java
> -}
Same here, please rebase.

2023-01-11 05:03 UTC, oh-noey reviewed
Reviewed with detection specific comments. I haven't looked at anything else.

2023-01-12 00:10 UTC, eirikh1996 commented on modules/Movecraft/src/main/java/net/countercraft/movecraft/processing/tasks/detection/DetectionTask.java
> +        final InteriorBlockValidator validator = new InteriorBlockValidator();
done

2023-07-18 19:43 UTC, eirikh1996 commented
Requested changes made @TylerS1066

2023-09-02 19:30 UTC, TylerS1066 requested changes
I don't know enough about the details of the processing system to do a through review, but with Hazel's comments and knowing the issues with the water detection system, this algorithm needs to be re-thought.

2024-06-01 00:36 UTC, closed without merging